const $ = s => document.querySelector(s); let currentUser=null,currentCompetition=null;
document.querySelectorAll('.cube-face').forEach((face,index)=>{for(let i=0;i<9;i++){const sticker=document.createElement('i');sticker.style.background=['#d93636','#f58d27','#246be8','#1ea764','#fffdf2','#f1d534'][index];face.append(sticker)}});
const heroActions=document.createElement('div');heroActions.className='hero-actions';heroActions.innerHTML='<button class="button primary" id="heroCreate">Créer une compétition <b>→</b></button><button class="button secondary" id="heroBrowse">Voir les compétitions</button>';document.querySelector('.hero-text').after(heroActions);
const escape=v=>{const n=document.createElement('span');n.textContent=v||'';return n.innerHTML};
async function api(path,options={}){let r;try{r=await fetch(path,{headers:{'content-type':'application/json'},...options,body:options.body?JSON.stringify(options.body):undefined})}catch{throw Error('Le serveur Cubely est indisponible. Lancez le site avec start-cubely.cmd.')}const type=r.headers.get('content-type')||'';if(!type.includes('application/json'))throw Error('La route API ne répond pas correctement. Ouvrez Cubely via son serveur, pas directement comme fichier.');const d=await r.json();if(!r.ok)throw Error(d.error||'Erreur serveur');return d}
function notice(text='',type=''){const n=$('#message');n.textContent=text;n.className=`message ${type}`}
function view(id){document.querySelectorAll('[data-view]').forEach(x=>x.hidden=x.id!==id);scrollTo({top:0,behavior:'smooth'})}
async function session(){const {user}=await api('/api/auth/session');currentUser=user;$('#account').textContent=user?`${user.name} · Déconnexion`:'Se connecter';$('#account').onclick=user?logout:()=>view('auth');$('#create').hidden=!user;let create=$('#createNav');if(!create){create=document.createElement('button');create.id='createNav';create.className='button secondary';create.textContent='Créer';create.onclick=()=>$('#create').scrollIntoView({behavior:'smooth'});$('#account').before(create)}create.hidden=!user}
async function competitions(){const {competitions:items}=await api('/api/competitions');$('#list').innerHTML=items.length?items.map(c=>`<article class="event-card"><span class="event-tag">${escape(c.event)}</span><h3>${escape(c.title)}</h3><p>Organisée par ${escape(c.organizer)} · ${c.participant_count} participant${c.participant_count>1?'s':''}</p><div class="event-meta"><span>${c.has_order?'Ordre configuré':'Aucun ordre'}</span><button class="join" data-id="${c.id}">Voir →</button></div></article>`).join(''):'<div class="empty-state">Aucune compétition disponible.</div>';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>open(b.dataset.id))}
async function open(id){currentCompetition=await api(`/api/competitions/${id}`);renderCompetition();view('competition')}
function renderCompetition(){const {competition,matches,order_state}=currentCompetition;$('#ctitle').textContent=competition.title;$('#cmeta').textContent=`${competition.event} · Organisée par ${competition.organizer}`;$('#join').hidden=!currentUser||competition.is_joined;$('#join').onclick=join;$('#order').innerHTML=matches.length?matches.map(m=>`<li class="match ${m.status}"><b>Match ${m.position}</b><span>${escape(m.player_a)} <i>vs</i> ${escape(m.player_b)}</span><small>${m.status==='live'?'EN COURS':m.status==='completed'?'Terminé':'À venir'}</small></li>`).join(''):`<li class="empty-state">${order_state==='draft'?'L’ordre est en préparation.':'Aucun ordre de passage publié.'}</li>`;$('#organizer').hidden=!competition.is_owner;if(competition.is_owner)organizer()}
function row(m,n,players){const opts=s=>`<option value="">Sélectionner</option>${players.map(p=>`<option value="${p.id}" ${Number(s)===p.id?'selected':''}>${escape(p.name)}</option>`).join('')}`;return `<div class="match-edit" draggable="true"><span class="drag">⠿</span><b>Match <span class="position">${n}</span></b><select class="a">${opts(m.player_a_id)}</select><span>vs</span><select class="b">${opts(m.player_b_id)}</select><button type="button" class="remove">×</button></div>`}
function organizer(){const {participants,matches,order_state}=currentCompetition;$('#state').textContent=order_state==='empty'?'Aucun ordre configuré':order_state==='draft'?'Brouillon':'Publié';const editor=$('#editor');editor.innerHTML=participants.length<2?'<p class="empty-state">Deux compétiteurs sont nécessaires.</p>':matches.map((m,i)=>row(m,i+1,participants)).join('')+'<button class="button secondary" type="button" id="add">+ Ajouter un affrontement</button>';$('#add')?.addEventListener('click',()=>{editor.insertAdjacentHTML('beforeend',row({},editor.querySelectorAll('.match-edit').length+1,participants));bind()});bind();$('#save').onclick=save;$('#publish').onclick=publish}
function bind(){let dragging;$('#editor').querySelectorAll('.match-edit').forEach(r=>{r.querySelector('.remove').onclick=()=>{r.remove();number()};r.ondragstart=()=>dragging=r;r.ondragover=e=>{e.preventDefault();if(dragging&&dragging!==r)r.before(dragging)}})}
function number(){$('#editor').querySelectorAll('.match-edit').forEach((r,i)=>r.querySelector('.position').textContent=i+1)}
function matches(){number();return[...$('#editor').querySelectorAll('.match-edit')].map((r,i)=>({position:i+1,player_a_id:+r.querySelector('.a').value,player_b_id:+r.querySelector('.b').value}))}
async function save(){try{const m=matches();if(m.some(x=>!x.player_a_id||!x.player_b_id||x.player_a_id===x.player_b_id))throw Error('Choisissez deux compétiteurs différents par match.');currentCompetition=await api(`/api/competitions/${currentCompetition.competition.id}/matches`,{method:'PUT',body:{matches:m}});renderCompetition();notice('Brouillon enregistré.','success')}catch(e){notice(e.message,'error')}}
async function publish(){await save();currentCompetition=await api(`/api/competitions/${currentCompetition.competition.id}/publish`,{method:'POST',body:{}});renderCompetition();notice('Ordre publié.','success')}
async function join(){try{currentCompetition=await api(`/api/competitions/${currentCompetition.competition.id}/join`,{method:'POST'});renderCompetition();notice('Inscription enregistrée.','success')}catch(e){notice(e.message,'error')}}
async function logout(){await api('/api/auth/logout',{method:'POST'});await session();view('home')}
$('#authform').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{const d=await api(`/api/auth/${$('#mode').value}`,{method:'POST',body:{name:f.get('name'),email:f.get('email'),password:f.get('password'),remember:f.get('remember')==='on'}});currentUser=d.user;await session();view('home');notice('Session sécurisée ouverte.','success')}catch(x){notice(x.message,'error')}};
$('#toggle').onclick=()=>{const register=$('#mode').value==='login';$('#mode').value=register?'register':'login';$('#name').hidden=!register;$('#authheading').textContent=register?'Créer un compte':'Connexion';$('#submit').textContent=register?'Créer mon compte':'Se connecter';$('#toggle').textContent=register?'J’ai déjà un compte':'Créer un compte'};
$('#createform').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{currentCompetition=await api('/api/competitions',{method:'POST',body:{title:f.get('title'),event:f.get('event'),scheduled_at:f.get('scheduled_at')||null}});await competitions();renderCompetition();view('competition');notice('Compétition créée.','success')}catch(x){notice(x.message,'error')}};
document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>view('home'));if(location.protocol==='file:'){notice('Cette copie a été ouverte directement. Fermez cet onglet puis double-cliquez sur OUVRIR-CUBELY.cmd.','error');$('#list').innerHTML='<div class="empty-state">Pour activer les comptes et la base de données, utilisez OUVRIR-CUBELY.cmd dans le dossier Cubely.</div>';$('#account').onclick=()=>notice('Double-cliquez sur OUVRIR-CUBELY.cmd pour ouvrir la version fonctionnelle.','error')}else{Promise.all([session(),competitions()]).catch(e=>notice(e.message,'error'))}
$('#heroCreate').onclick=()=>{if(currentUser){$('#create').scrollIntoView({behavior:'smooth'})}else{view('auth');notice('Connectez-vous ou créez un compte pour organiser une compétition.')}};$('#heroBrowse').onclick=()=>$('#list').closest('.events').scrollIntoView({behavior:'smooth'});
