const WCA_EVENTS=['2x2x2 Cube','3x3x3 Cube','4x4x4 Cube','5x5x5 Cube','6x6x6 Cube','7x7x7 Cube','3x3x3 Blindfolded','3x3x3 Fewest Moves','3x3x3 One-Handed','Clock','Megaminx','Pyraminx','Skewb','Square-1','4x4x4 Blindfolded','5x5x5 Blindfolded','3x3x3 Multi-Blind'];
const events=[{name:'Casablanca Cube Open',event:'3×3×3 CUBE',people:24,time:'Démarre dans 18 min'},{name:'Sunday Pyraminx Jam',event:'PYRAMINX',people:12,time:'En cours · Round 2'},{name:'Maghreb Speed Night',event:'2×2×2 CUBE',people:38,time:'Démarre dans 1 h 40'}];
let contestants=[['1','AM','Amine B.','8.42'],['2','SL','Sofia L.','9.01'],['3','MR','Mehdi R.','9.38'],['4','NK','Nora K.','10.12'],['5','YA','Youssef A.','10.46']];
const people=[['AM','Amine B.','8.42','ready'],['SL','Sofia L.','9.01','solving'],['MR','Mehdi R.','9.38','ready'],['NK','Nora K.','10.12','ready'],['YA','Youssef A.','10.46','ready'],['LY','Vous','—','ready']];
const moves={'2x2x2 Cube':['R','U','F'],'3x3x3 Cube':['R','L','U','D','F','B'],'4x4x4 Cube':['Rw','Lw','Uw','Dw','F','B'],'5x5x5 Cube':['3Rw','Rw','U','D','F','B'],'6x6x6 Cube':['3Rw','Rw','U','D','F','B'],'7x7x7 Cube':['3Rw','Rw','U','D','F','B'],Pyraminx:['R','L','U','B'],Skewb:['R','L','U','B'],Megaminx:['R++','D--','U'],'Square-1':['(1,0)','(3,-2)','/'],Clock:['UR','DR','DL','UL','ALL']};
let elapsed=0,interval,running=false,finished=false,penalty='',stream,sharedIndex=1,authCreate=false,drag=false,lastX=0,lastY=0,rx=-24,ry=35;
function renderEvents(){eventGrid.innerHTML=events.map((e,i)=>`<article class="event-card"><div class="event-card-top"><span class="event-tag">${e.event}</span><span class="dot green"></span></div><h3>${e.name}</h3><p>${e.time}</p><div class="event-meta"><span>◉ ${e.people} participants</span><button class="join" onclick="joinEvent(${i})">Rejoindre →</button></div></article>`).join('')}
function renderRanking(){rankingList.innerHTML=contestants.map(c=>`<div class="rank-row"><span class="rank">${c[0]}</span><span class="ravatar">${c[1]}</span><b>${c[2]}</b><small>${c[3]}</small></div>`).join('')}
function renderPeople(){competitorList.innerHTML=people.map(p=>`<div class="competitor-row"><i class="presence ${p[3]==='solving'?'solving':''}"></i><span class="mini-avatar">${p[0]}</span><b>${p[1]}</b><small>${p[3]==='solving'?'EN COURS':p[2]}</small></div>`).join('');participantCount.textContent=people.length}
function renderCameras(){cameraGrid.innerHTML=[['AM','Amine B.'],['SL','Sofia L.']].map(x=>`<div class="cam-tile"><span class="cam-avatar">${x[0]}</span><i class="cam-live">● LIVE</i><b>${x[1]}</b><button onclick="organizerCamera('${x[1]}')">⛶</button></div>`).join('')}
function renderChat(){chatMessages.innerHTML=[['Amine B.','Bonne chance à tous !','18:31'],['Sofia L.','Le scramble est bien reçu.','18:32'],['Organisateur','Scramble #1 lancé pour tous les compétiteurs.','18:33']].map(m=>`<div class="chat-message"><b>${m[0]}</b>${m[1]}<time>${m[2]}</time></div>`).join('')}
function showView(view){document.querySelectorAll('.app-view').forEach(e=>e.classList.add('hidden'));document.querySelector('main').classList.toggle('hidden',view!=='home');if(view!=='home')document.getElementById(view).classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});if(view==='room'){renderRanking();renderPeople();renderCameras();renderChat();buildCube();newScramble()}}
function joinEvent(i){roomName.textContent=events[i].name;showView('room')}
function createCompetition(e){e.preventDefault();roomName.textContent=e.target.querySelector('input').value;const event=eventType.value;roomEvent.textContent=event+' · Average of 5';currentEvent.childNodes[0].nodeValue=event+' ';showView('room');toast('Brouillon créé : utilisez Sauvegarder la compétition pour le conserver.')}
function toggleAuthMode(){authCreate=!authCreate;authTitle.textContent=authCreate?'Créer votre profil':'Bienvenue';document.querySelector('.auth-switch').textContent=authCreate?'Déjà membre ? Se connecter':'Pas encore de compte ? Créer un profil'}
function authenticate(e){e.preventDefault();const name=authName.value.trim()||'Yassine';accountButton.querySelector('b').textContent=name;accountButton.onclick=()=>showView('profile');toast(authCreate?'Profil créé localement.':'Connexion locale établie.');showView('home')}
function format(ms){return (ms/1000).toFixed(2)}function updateTimer(){elapsed+=10;timer.textContent=format(elapsed)}
function toggleTimer(){if(finished)return;if(!running){running=true;people[5][3]='solving';solverStatus.textContent='Vous êtes en résolution';timer.classList.add('running');timerState.textContent='RÉSOLUTION EN COURS';timerHint.textContent='Votre statut est partagé avec la salle';interval=setInterval(updateTimer,10);renderPeople()}else{running=false;finished=true;people[5][3]='ready';clearInterval(interval);timer.classList.remove('running');timerState.textContent='TEMPS TERMINÉ — AJOUTEZ UNE PÉNALITÉ SI NÉCESSAIRE';timerHint.textContent='Votre temps';saveResult.disabled=false;renderPeople()}}
function saveResult(){if(!finished)return;let result=penalty==='DNF'?'DNF':format(elapsed)+(penalty==='+2'?' +2':'');contestants.push(['—','LY','Vous',result]);renderRanking();document.querySelector('.you-row').innerHTML=`<span>Votre position</span><b>#${contestants.length}</b><small>${result} · temporaire</small>`;toast('Résultat temporaire ajouté — sauvegardez-le pour le conserver.');elapsed=0;finished=false;penalty='';timer.textContent='0.00';timerState.textContent='PRÊT';timerHint.textContent='Appuyez sur ESPACE pour commencer';saveResult.disabled=true;document.querySelectorAll('.penalty').forEach(x=>x.classList.remove('selected'))}
function setPenalty(p){penalty=penalty===p?'':p;document.querySelectorAll('.penalty').forEach(x=>x.classList.toggle('selected',x.textContent===penalty))}
function newScramble(){let event=eventType?.value||'3x3x3 Cube',pool=moves[event]||moves['3x3x3 Cube'],last='',s=[];while(s.length<20){let m=pool[Math.floor(Math.random()*pool.length)],suf=['','\'','2'][Math.floor(Math.random()*3)];if(m!==last){s.push(m+suf);last=m}}scramble.textContent=s.join(' ');applyScrambleVisual(s)}
function nextSharedScramble(){sharedIndex++;sharedRound.textContent='#'+sharedIndex;scrambleNumber.textContent='#'+sharedIndex+' pour tous';newScramble();toast('Scramble commun #'+sharedIndex+' envoyé à tous les compétiteurs.')}
function buildCube(){document.querySelectorAll('.cube-face').forEach((face,fi)=>{if(!face.children.length)for(let i=0;i<9;i++){let s=document.createElement('i');s.style.background=['#d93636','#f58d27','#246be8','#1ea764','#fffdf2','#f1d534'][fi];face.appendChild(s)}})}
function applyScrambleVisual(tokens){document.querySelectorAll('.cube-face i').forEach((s,i)=>{s.style.filter=`saturate(${.78+(i%3)*.1}) brightness(${.78+((i+tokens.length)%4)*.06})`;if(i%7===0)s.style.transform=`rotate(${tokens.length*7}deg)`})}
function initCubeDrag(){document.querySelectorAll('.cube3d').forEach(cube=>{let isDragging=false,x=0,y=0,cubeX=-24,cubeY=35;const move=e=>{if(!isDragging)return;cubeY+=(e.clientX-x)*.5;cubeX-=(e.clientY-y)*.5;x=e.clientX;y=e.clientY;cube.style.transform=`rotateX(${cubeX}deg) rotateY(${cubeY}deg)`};cube.addEventListener('pointerdown',e=>{isDragging=true;x=e.clientX;y=e.clientY;cube.setPointerCapture(e.pointerId)});cube.addEventListener('pointermove',move);cube.addEventListener('pointerup',()=>isDragging=false);cube.addEventListener('pointercancel',()=>isDragging=false)})}
async function toggleCamera(){try{if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;video.classList.add('hidden');cameraBtn.textContent='◉ Activer la caméra';toast('Votre caméra est désactivée.')}else{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});video.srcObject=stream;video.classList.remove('hidden');cameraBtn.textContent='◉ Caméra active';toast('Caméra active : le partage requiert l’accord explicite du participant.')}}catch(e){toast('Autorisation caméra nécessaire pour l’activer.')}}
function organizerCamera(name){toast('Commande organisateur : contrôle de la caméra de '+name+'. À connecter au serveur temps réel.')}
function toggleCameraGrid(){cameraGrid.classList.toggle('hidden')}function toggleChat(){chatMessages.classList.toggle('hidden');document.querySelector('.chat-form').classList.toggle('hidden')}
function sendMessage(e){e.preventDefault();const text=chatInput.value.trim();if(!text)return;const m=document.createElement('div');m.className='chat-message';m.innerHTML=`<b>Vous</b>${text}<time>${new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</time>`;chatMessages.appendChild(m);chatMessages.scrollTop=chatMessages.scrollHeight;chatInput.value=''}
function saveCompetition(){localStorage.setItem('cubely-competition',JSON.stringify({name:roomName.textContent,event:roomEvent.textContent,savedAt:Date.now()}));draftState.textContent='SAUVEGARDÉE';toast('Compétition sauvegardée sur cet appareil.')}
function saveResults(){localStorage.setItem('cubely-results',JSON.stringify(contestants));toast('Résultats sauvegardés sur cet appareil.')}
function deleteCompetition(){if(confirm('Supprimer cette compétition et ses données locales sauvegardées ?')){localStorage.removeItem('cubely-competition');localStorage.removeItem('cubely-results');toast('Compétition supprimée.');showView('home')}}
function copyInvite(){navigator.clipboard?.writeText(location.href+'?join='+encodeURIComponent(roomName.textContent));toast('Lien unique de compétition copié !')}
function toast(text){const t=document.querySelector('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!document.getElementById('room').classList.contains('hidden')){e.preventDefault();toggleTimer()}});eventType.innerHTML=WCA_EVENTS.map(e=>`<option>${e}</option>`).join('');renderEvents();renderRanking();buildCube();initCubeDrag();
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.cube3d').forEach(cube=>{let active=false,lastX=0,lastY=0;const computed=getComputedStyle(cube);let rotateX=parseFloat(computed.getPropertyValue('--cube-x'))||-24,rotateY=parseFloat(computed.getPropertyValue('--cube-y'))||35;const finish=e=>{active=false;if(cube.hasPointerCapture?.(e.pointerId))cube.releasePointerCapture(e.pointerId)};cube.addEventListener('pointerdown',e=>{active=true;lastX=e.clientX;lastY=e.clientY;cube.setPointerCapture(e.pointerId);e.preventDefault()});cube.addEventListener('pointermove',e=>{if(!active)return;rotateY+=(e.clientX-lastX)*.5;rotateX-=(e.clientY-lastY)*.5;lastX=e.clientX;lastY=e.clientY;cube.style.setProperty('--cube-x',`${rotateX}deg`,'important');cube.style.setProperty('--cube-y',`${rotateY}deg`,'important')});cube.addEventListener('pointerup',finish);cube.addEventListener('pointercancel',finish)})});
